### ISSUE TITLE
Error Installing the Repo

### ISSUE THREAD

**Issue by hangtime79** [IBMPredictiveAnalytics/rCharts_Basic_Charts#2]
Hey Greg,

Tried to do the installation, but was only creating null files in the output. I went into R Studio and I'm getting an error when trying to install the Repo. Here is the R Studio output. Its throwing an error on a missing package, base64enc.

Grant

`> # Install packages   -Need to get rCharts from GitHub - no binary for 3.1

> list.of.packages <- c( "devtools", 'RCurl')
> new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
> if(length(new.packages)) install.packages(new.packages)
> 
> library(devtools)
> if (! ("rCharts" %in% rownames(installed.packages()))) {install_github("ramnathv/rCharts@dev") }
> Downloading GitHub repo ramnathv/rCharts@dev
> Installing rCharts
> "C:/PROGRA~1/R/R-31~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
>   "C:/Users/IBM_ADMIN/AppData/Local/Temp/RtmpiaxW7k/devtools41d464674748/ramnathv-rCharts-8d3fe35"  \
>   --library="C:/Users/IBM_ADMIN/Documents/R/win-library/3.1" --install-tests 
- installing _source_ package 'rCharts' ...
  *\* R
  *\* inst
  *\* preparing package for lazy loading
  Error in loadNamespace(name) : there is no package called 'base64enc'
  Error : unable to load R code in package 'rCharts'
  ERROR: lazy loading failed for package 'rCharts'
- removing 'C:/Users/IBM_ADMIN/Documents/R/win-library/3.1/rCharts'
  Show Traceback
  
  Rerun with Debug
  Error: Command failed (1) > library("rCharts")
  Error in library("rCharts") : there is no package called ‘rCharts’
  
  > options(
-     rcharts.mode = 'iframesrc', 
-     rcharts.cdn = F,
-     RCHART_WIDTH =  800,
-     RCHART_HEIGHT = 400
- )`

**Comment by gfilla** [comment]
Hi Grant - 

I just added a new .cfe in the src folder can you try it out?  I was able to replicate the issue and saw the base64enc package is a new dependency for R 3.2.  I'm going to close this for now, the updated version does not work please re open.  Thanks for reporting.
